### ISSUE TITLE
Stable relase

### ISSUE THREAD

**Issue by mimol91** [xsolve-pl/xsolve-associate#3]
Hey.
I :heart:  this lib (and I am not even using to collect associated object, but just to reduce number of DB queries).

One simple line (I am using it in sf project)
` $this->get('core.doctrine.optimizer')->collect($matches->toArray(), ['player', 'playerPosition'])` and number of queries drops (and you do not have to change any query to add join's) just Amazing!

Will it be possible to create an stable release?

**Comment by malef** [comment]
That was the idea, glad to hear you like it and that it is useful for you. :+1: 

If you think this version is good enough I would be happy to tag it with `1.0.0` and leave all the improvements for future versions. Let me know what's your take on this.

**Comment by malef** [comment]
BTW, have you done any performance tests with and without this library? I would be curious to find out how much does it help (how much the number of queries drops, how much it speeds up the request etc.).

**Comment by mimol91** [comment]
I've just start to using- it in places where I think that it can reudce number of queries.
I didnt have too much time, to look for this places.
I've test it in 'real' application in single place. It reduce number of queruies from over 30 to around 15. (sql-time was reduced aswell, however I cant remind exact times)

**Comment by mimol91** [comment]
@malef Thanks
