### ISSUE TITLE
Drop support for php < 7.1

### ISSUE THREAD

**Issue by mimol91** [xsolve-pl/xsolve-associate#5]
What do you think about dropping support for php 7.1?

Benefits:
- Nullable return types https://github.com/xsolve-pl/xsolve-associate/blob/master/lib/Metadata/MetadataWrapperProvider.php#L33 
- iterable https://github.com/xsolve-pl/xsolve-associate/blob/master/lib/Collector.php#L25  Can use `ArrayCollection`
- `IterableCollectionTraversalStrategy` instead separate for array/traversable

**Comment by malef** [comment]
I've dicussed this with some colleagues and for version 2.0 this library will require PHP ^7.1. Stay tuned!
